
services:
  identity-service:
    image: gymproject-identity-service
    build:
      context: .
      dockerfile: GymProject.IdentityService/Dockerfile
    ports:
      - "5263:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=GymProject_IdentityDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;
    depends_on:
      sql-server:
        condition: service_healthy

  fitness-service:
    image: gymproject-fitness-service
    build:
      context: .
      dockerfile: GymProject.FitnessService/Dockerfile
    ports:
      - "5020:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=GymProject_FitnessDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;
      # Base address for calling identity
      - IdentityServiceUrl=http://identity-service:8080
    depends_on:
      sql-server:
        condition: service_healthy
      identity-service:
        condition: service_started

  nutrition-service:
    image: gymproject-nutrition-service
    build:
      context: .
      dockerfile: NutritionService/Dockerfile
    ports:
      - "5030:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=GymProject_NutritionDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;
      - IdentityServiceUrl=http://identity-service:8080/
    depends_on:
      sql-server:
        condition: service_healthy
      identity-service:
        condition: service_started

  api-gateway:
    image: gymproject-api-gateway
    build:
      context: .
      dockerfile: GymProject.Gateway/Dockerfile
    ports:
      - "5134:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ReverseProxy__Clusters__identity-cluster__Destinations__destination1__Address=http://identity-service:8080
      - ReverseProxy__Clusters__fitness-cluster__Destinations__destination1__Address=http://fitness-service:8080
      - ReverseProxy__Clusters__nutrition-cluster__Destinations__destination1__Address=http://nutrition-service:8080
    depends_on:
      - identity-service
      - fitness-service
      - nutrition-service

  frontend:
    image: gymproject-frontend
    build:
      context: ./GymProject.Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api-gateway

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"YourStrong@Password123\" -Q \"SELECT 1\" -C"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - gymproject-sql-data:/var/opt/mssql

volumes:
  gymproject-sql-data:
